export const sharedStyles = {
    pageContainer: 'page-container',
    gradientBg: 'gradient-bg',
    imageBg: 'image-bg',
    contentContainer: 'content-container',
    wideContentContainer: 'wide-content-container',
    heading: 'heading',
    form: 'form',
    input: 'input',
    select: 'select',
    button: 'button',
    label: 'label',
    errorText: 'error-text',
    successText: 'success-text',
};